INSERT INTO "subscription_plan_catalog" (
  "id",
  "code",
  "audience",
  "tier",
  "title",
  "group_description",
  "icon_key",
  "label",
  "cta",
  "description",
  "badge",
  "currency",
  "monthly_price_cents",
  "yearly_monthly_price_cents",
  "storage_bytes",
  "max_resources",
  "max_tutorials",
  "max_collections",
  "can_create_content",
  "max_search_results",
  "feature_values",
  "pbac",
  "metadata",
  "display_order",
  "active",
  "created_at",
  "updated_at"
) VALUES
(
  'CREATOR_FREE',
  'CREATOR_FREE',
  'CREATOR',
  'free',
  'Creator',
  'Build your audience and monetize your expertise.',
  'Palette',
  'Free',
  'Start Creating',
  'Get started with essential creator tools.',
  NULL,
  'USD',
  0,
  NULL,
  524288000,
  5,
  3,
  2,
  TRUE,
  20,
  '[{"label":"Storage","value":"500 MB"},{"label":"Resources","value":"Up to 5"},{"label":"Tutorials","value":"Up to 3"},{"label":"Collections","value":"Up to 2"},{"label":"Analytics dashboard","value":true},{"label":"Advanced analytics","value":false},{"label":"Custom branding","value":false},{"label":"Priority review","value":false},{"label":"Discord support","value":false},{"label":"Revenue share","value":"85%"}]'::jsonb,
  '{"content:create":true,"content:autoReview":false,"content:customBranding":false,"support:priority":false}'::jsonb,
  '{"audienceKey":"creatorPlans"}'::jsonb,
  10,
  TRUE,
  NOW(),
  NOW()
),
(
  'CREATOR_PRO',
  'CREATOR_PRO',
  'CREATOR',
  'pro',
  'Creator',
  'Build your audience and monetize your expertise.',
  'Palette',
  'Creator Pro',
  'Upgrade to Pro',
  'Scale your content empire with unlimited power.',
  'Most Popular',
  'USD',
  999,
  799,
  53687091200,
  -1,
  -1,
  -1,
  TRUE,
  -1,
  '[{"label":"Storage","value":"50 GB"},{"label":"Resources","value":"Unlimited"},{"label":"Tutorials","value":"Unlimited"},{"label":"Collections","value":"Unlimited"},{"label":"Analytics dashboard","value":true},{"label":"Advanced analytics","value":true},{"label":"Custom branding","value":true},{"label":"Priority review","value":true},{"label":"Discord support","value":true},{"label":"Revenue share","value":"92%"}]'::jsonb,
  '{"content:create":true,"content:autoReview":true,"content:customBranding":true,"support:priority":true}'::jsonb,
  '{"audienceKey":"creatorPlans"}'::jsonb,
  20,
  TRUE,
  NOW(),
  NOW()
),
(
  'STUDENT_FREE',
  'STUDENT_FREE',
  'STUDENT',
  'free',
  'Student',
  'Learn smarter with tools designed for students.',
  'Users',
  'Free',
  'Start Learning',
  'Access free resources and start your journey.',
  NULL,
  'USD',
  0,
  NULL,
  1073741824,
  0,
  0,
  0,
  FALSE,
  10,
  '[{"label":"Storage","value":"1 GB"},{"label":"Data protection","value":false},{"label":"Collection discount","value":"—"},{"label":"Content preview","value":"Standard"},{"label":"Auto-review content","value":false},{"label":"Bookmark & organize","value":true},{"label":"Offline access","value":false},{"label":"Discord support","value":false},{"label":"Early access","value":false},{"label":"Ad-free experience","value":false}]'::jsonb,
  '{"content:create":false,"learning:dataProtection":false,"learning:offlineAccess":false,"learning:adFree":false}'::jsonb,
  '{"audienceKey":"studentPlans"}'::jsonb,
  30,
  TRUE,
  NOW(),
  NOW()
),
(
  'STUDENT_PRO',
  'STUDENT_PRO',
  'STUDENT',
  'pro',
  'Student',
  'Learn smarter with tools designed for students.',
  'Users',
  'Student Pro',
  'Upgrade to Pro',
  'Unlock the full learning experience.',
  'Best Value',
  'USD',
  499,
  399,
  26843545600,
  0,
  0,
  0,
  FALSE,
  -1,
  '[{"label":"Storage","value":"25 GB"},{"label":"Data protection","value":true},{"label":"Collection discount","value":"15% off"},{"label":"Content preview","value":"Extended"},{"label":"Auto-review content","value":true},{"label":"Bookmark & organize","value":true},{"label":"Offline access","value":true},{"label":"Discord support","value":true},{"label":"Early access","value":true},{"label":"Ad-free experience","value":true}]'::jsonb,
  '{"content:create":false,"learning:dataProtection":true,"learning:offlineAccess":true,"learning:adFree":true}'::jsonb,
  '{"audienceKey":"studentPlans"}'::jsonb,
  40,
  TRUE,
  NOW(),
  NOW()
)
ON CONFLICT ("code") DO UPDATE SET
  "audience" = EXCLUDED."audience",
  "tier" = EXCLUDED."tier",
  "title" = EXCLUDED."title",
  "group_description" = EXCLUDED."group_description",
  "icon_key" = EXCLUDED."icon_key",
  "label" = EXCLUDED."label",
  "cta" = EXCLUDED."cta",
  "description" = EXCLUDED."description",
  "badge" = EXCLUDED."badge",
  "currency" = EXCLUDED."currency",
  "monthly_price_cents" = EXCLUDED."monthly_price_cents",
  "yearly_monthly_price_cents" = EXCLUDED."yearly_monthly_price_cents",
  "storage_bytes" = EXCLUDED."storage_bytes",
  "max_resources" = EXCLUDED."max_resources",
  "max_tutorials" = EXCLUDED."max_tutorials",
  "max_collections" = EXCLUDED."max_collections",
  "can_create_content" = EXCLUDED."can_create_content",
  "max_search_results" = EXCLUDED."max_search_results",
  "feature_values" = EXCLUDED."feature_values",
  "pbac" = EXCLUDED."pbac",
  "metadata" = EXCLUDED."metadata",
  "display_order" = EXCLUDED."display_order",
  "active" = EXCLUDED."active",
  "updated_at" = NOW();
