export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const RESOURCE_REPOSITORY = Symbol('RESOURCE_REPOSITORY');
export const TUTORIAL_REPOSITORY = Symbol('TUTORIAL_REPOSITORY');
export const COLLECTION_REPOSITORY = Symbol('COLLECTION_REPOSITORY');
export const MAJOR_REPOSITORY = Symbol('MAJOR_REPOSITORY');
export const COURSE_REPOSITORY = Symbol('COURSE_REPOSITORY');
export const CONTENT_VALIDATION_SERVICE = Symbol('CONTENT_VALIDATION_SERVICE');
