export const USER_REPOSITORY = Symbol('USER_PROFILE_REPOSITORY');
export const CAREER_REPOSITORY = Symbol('CAREER_REPOSITORY');
export const HIGHLIGHT_SKILL_REPOSITORY = Symbol('HIGHLIGHT_SKILL_REPOSITORY');
export const FOLLOW_REPOSITORY = Symbol('FOLLOW_REPOSITORY');
export const USER_RATING_REPOSITORY = Symbol('USER_RATING_REPOSITORY');
