export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const OTP_REPOSITORY = Symbol('OTP_REPOSITORY');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
