/* eslint-disable @typescript-eslint/no-explicit-any */
"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js"
import { configureBoneyard } from "boneyard-js/react"

import _collection_card from "./collection-card.bones.json"
import _explore_page from "./explore-page.bones.json"
import _home_page from "./home-page.bones.json"
import _profile_item_card from "./profile-item-card.bones.json"
import _resource_card from "./resource-card.bones.json"
import _resource_detail from "./resource-detail.bones.json"
import _tutorial_card from "./tutorial-card.bones.json"

configureBoneyard({
  color: "hsl(240 5.9% 90%)",
  darkColor: "hsl(240 3.7% 25%)",
  animate: "shimmer",
  shimmerColor: "hsl(240 4.8% 95.9%)",
  darkShimmerColor: "hsl(240 3.7% 32%)",
  speed: "2s",
  shimmerAngle: 110,
  stagger: 80,
  transition: 300,
})

registerBones({
  "resource-card": _resource_card as any,
  "tutorial-card": _tutorial_card as any,
  "collection-card": _collection_card as any,
  "profile-item-card": _profile_item_card as any,
  "resource-detail": _resource_detail as any,
  "home-page": _home_page as any,
  "explore-page": _explore_page as any,
})
